// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwkzjalnzktfzqycytbr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3a3pqYWxuemt0ZnpxeWN5dGJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2MTUwODksImV4cCI6MjA5MDE5MTA4OX0.dEukM3VqmZNtZOmpkSiBfsBrUDuPwjiRg7PfH_hvB7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});